[build-system]
requires = ["uv_build>=0.9.10,<0.10.0"]
build-backend = "uv_build"

[project]
name = "pdfitdown-docs"
version = "0.2.0"
description = "Package to manage PdfItDown docs"
requires-python = ">=3.10,<3.14"
dependencies = [
    "pdfitdown[server]",
    "pdfitdown-mcp-server",
]

[tool.uv.sources]
pdfitdown = {workspace = true}
pdfitdown-mcp-server = {workspace = true}

[project.scripts]
api-docs = "pdfitdown_docs.api_reference:main"

[tool.uv.build-backend]
module-name = "pdfitdown_docs"
