[project]
name = "pdfitdown-docs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pdfitdown[server]",
]

[tool.uv.sources]
pdfitdown = {workspace = true}